# -*- coding: utf-8 -*-
"""easy_fruad_dataction.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1r6PJqLLoCOQoNB2isD0CW_-4abKRyfey
"""

import pandas as pd
import numpy as np

df=pd.read_csv("/content/credit_card_fraud_synthetic.csv")

df.head()

df.shape

df.isnull().sum()

df.columns

df["Class"].value_counts()

(round(df["Class"].value_counts(normalize=True)*100,2))

df.describe()

df.corr()["Class"].sort_values(ascending=False)

import matplotlib.pyplot  as plt
import seaborn as sns

plt.figure(figsize=(5,4))
df["Class"].value_counts().plot(kind="bar",color=["skyblue","orange"])
plt.xticks([0,1],["No Fraud","Fraud"],rotation=0)
plt.title("all_class")
plt.show()

plt.figure(figsize=(4,4))
sns.heatmap(df.corr(),annot=True,cmap="coolwarm")
plt.title("corelation_heatmap")
plt.show()

sns.boxplot(x="Class",y="Amount",data=df)
plt.title("amount by class")
plt.show()

from sklearn.model_selection import train_test_split
x=df.drop("Class",axis=1)
y=df["Class"]
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=42)
x_train.shape
y_train.value_counts()

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report,confusion_matrix
model=LogisticRegression(max_iter=1000)
model.fit(x_train,y_train)
y_pred=model.predict(x_test)
classification_report(y_test,y_pred,target_names=["No fraud","Fraud"])
confusion_matrix(y_test,y_pred)

model_balanced=LogisticRegression(max_iter=1000,class_weight="balanced")
model_balanced.fit(x_train,y_train)
y_pred_bal=model_balanced.predict(x_test)
classification_report(y_test,y_pred_bal,target_names=["No_fraud","Fraud"])
confusion_matrix(y_test,y_pred_bal)



